# Generated by Django 4.1.5 on 2023-02-06 22:10

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=users.utils.generate_username, max_length=50, unique=True),
        ),
    ]
